### ISSUE TITLE
哈喽哈喽  可以加个联系方式吗

### ISSUE THREAD

**Issue by pinkina** [LifeAlsoIsGG/SupermarketSystem-Homework#2]
问一下细节

**Comment by LifeIsAlsoGG** [comment]
不好意思，很多细节我也不太清楚了

**Comment by draconidss** [comment]
不好意思，很多细节我也不太清楚了

**Comment by pinkina** [comment]
嗷嗷～好趴没事&nbsp;&nbsp;&nbsp;你这个做得很棒！！谢谢分享


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月12日(周三) 中午1:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LifeIsAlsoGG/project-supermarket-system-java] 哈喽哈喽  可以加个联系方式吗 (Issue #2)




 
不好意思，很多细节我也不太清楚了
 
&mdash;

**Comment by draconidss** [comment]
但非常不推荐你用这个框架技术了，java 的还是 SSM 吧，不过业务实现可以参考罗（虽然这个逻辑代码在这个 swing 框架写的很乱）

**Comment by pinkina** [comment]
嗷大佬&nbsp;&nbsp;可以加个wx吗？或许你这个系统可以这个最后关头救我命了😂😂


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月12日(周三) 中午1:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LifeIsAlsoGG/project-supermarket-system-java] 哈喽哈喽  可以加个联系方式吗 (Issue #2)




 
但非常不推荐你用这个框架技术了，java 的还是 SSM 吧，不过业务实现可以参考罗（虽然这个逻辑代码在这个 swing 框架写的很乱）
 
&mdash;
